home_page12:
    path:     /index1
    defaults: { _controller: FrontBundle:Pages:index }

detai_produit:
    path:    /{id}/detailProduit/
    defaults: { _controller: FrontBundle:DetailProduit:readById }



