entity_homepage:
        path:     /
        defaults: { _controller: EntityBundle:Default:index }

entity_commande:
        resource: "@EntityBundle/Resources/config/commande.yml"
        prefix:   /commande

entity_detailcommande:
        resource: "@EntityBundle/Resources/config/detailcommande.yml"
        prefix:   /detailcommande

panier:
        resource: "@EntityBundle/Resources/config/panier.yml"
        prefix:   /panier