front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

yosr:
    resource: "@YosrBundle/Resources/config/routing.yml"
    prefix:   /

seif:
    resource: "@SeifBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sofiene:
    resource: "@SofieneBundle/Resources/config/routing.yml"
    prefix:   /

wassim:
    resource: "@WassimBundle/Resources/config/routing.yml"
    prefix:   /

chaima:
    resource: "@ChaimaBundle/Resources/config/routing.yml"
    prefix:   /

mokhles:
    resource: "@MokhlesBundle/Resources/config/routing.yml"
    prefix:   /

entity:
    resource: "@EntityBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
