<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSw3ne7x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSw3ne7x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSw3ne7x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSw3ne7x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSw3ne7x\appProdProjectContainer(array(
    'container.build_hash' => 'Sw3ne7x',
    'container.build_id' => '8f7c5de0',
    'container.build_time' => 1546175756,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSw3ne7x');
