<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payment.form.paypal_express_checkout_type' shared service.

return $this->services['payment.form.paypal_express_checkout_type'] = new \JMS\Payment\PaypalBundle\Form\ExpressCheckoutType();
