<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payment.paypal.authentication_strategy.token' shared service.

return $this->services['payment.paypal.authentication_strategy.token'] = new \JMS\Payment\PaypalBundle\Client\Authentication\TokenAuthenticationStrategy('your_api_username', 'your_api_password', 'your_api_signature');
