<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'JMS\Payment\CoreBundle\Cryptography\DefusePhpEncryptionService' shared service.

return $this->services['JMS\Payment\CoreBundle\Cryptography\DefusePhpEncryptionService'] = new \JMS\Payment\CoreBundle\Cryptography\DefusePhpEncryptionService('');
