<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'JMS\Payment\CoreBundle\Command\GenerateKeyCommand' shared service.

$this->services['JMS\Payment\CoreBundle\Command\GenerateKeyCommand'] = $instance = new \JMS\Payment\CoreBundle\Command\GenerateKeyCommand();

$instance->setName('jms_payment_core:generate-key');

return $instance;
