<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payment.form.choose_payment_method_transformer' shared service.

return $this->services['payment.form.choose_payment_method_transformer'] = new \JMS\Payment\CoreBundle\Form\Transformer\ChoosePaymentMethodTransformer();
