<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payment.plugin.paypal_express_checkout' shared service.

return $this->services['payment.plugin.paypal_express_checkout'] = new \JMS\Payment\PaypalBundle\Plugin\ExpressCheckoutPlugin(NULL, NULL, ${($_ = isset($this->services['payment.paypal.client']) ? $this->services['payment.paypal.client'] : $this->load('getPayment_Paypal_ClientService.php')) && false ?: '_'}, NULL, NULL);
