<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payment.form.choose_payment_method_type' shared service.

$this->services['payment.form.choose_payment_method_type'] = $instance = new \JMS\Payment\CoreBundle\Form\ChoosePaymentMethodType(${($_ = isset($this->services['JMS\Payment\CoreBundle\PluginController\EntityPluginController']) ? $this->services['JMS\Payment\CoreBundle\PluginController\EntityPluginController'] : $this->load('getEntityPluginControllerService.php')) && false ?: '_'}, array('paypal_express_checkout' => 'JMS\\Payment\\PaypalBundle\\Form\\ExpressCheckoutType'));

$instance->setDataTransformer(${($_ = isset($this->services['payment.form.choose_payment_method_transformer']) ? $this->services['payment.form.choose_payment_method_transformer'] : ($this->services['payment.form.choose_payment_method_transformer'] = new \JMS\Payment\CoreBundle\Form\Transformer\ChoosePaymentMethodTransformer())) && false ?: '_'});

return $instance;
