entity_homepage:
    path:     /E
    defaults: { _controller: YosrBundle:Default:index }
entity_user_afficher:
    path:     /user/afficher
    defaults: { _controller: YosrBundle:User:afficher }
entity_Article_afficher:
    path:     /Article/afficher
    defaults: { _controller: YosrBundle:Article:afficher }
entity_Article_rechercher:
    path:     /Article/rechercher
    defaults: { _controller: YosrBundle:Article:rechercher }
entity_Article_ajouter:
    path:     /Article/ajouter
    defaults: { _controller: YosrBundle:Article:ajouter }
entity_Article_modifier:
    path:     /Article/modifier
    defaults: { _controller: YosrBundle:Article:modifier }
entity_Article_supprimer:
    path:     /Article/supprimer
    defaults: { _controller: YosrBundle:Article:supprimer }
entity_Article_trier:
    path:     /Article/tri
    defaults: { _controller: YosrBundle:Article:tri }

entity_CategArticle_afficher:
    path:     /CategArticle/afficher
    defaults: { _controller: YosrBundle:CategoryArticle:afficher }
entity_CategArticle_rechercher:
    path:     /CategArticle/rechercher
    defaults: { _controller: YosrBundle:CategoryArticle:rechercher }
entity_CategArticle_ajouter:
    path:     /CategArticle/ajouter
    defaults: { _controller: YosrBundle:CategoryArticle:ajouter }
entity_CategArticle_modifier:
    path:     /CategArticle/modifier
    defaults: { _controller: YosrBundle:CategoryArticle:modifier}
entity_CategArticle_supprimer:
    path:     /CategArticle/supprimer
    defaults: { _controller: YosrBundle:CategoryArticle:supprimer }