<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKjjxgpv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKjjxgpv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKjjxgpv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKjjxgpv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKjjxgpv\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kjjxgpv',
    'container.build_id' => 'ff5cf7dd',
    'container.build_time' => 1553180179,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKjjxgpv');
