<?php

namespace EntityBundle\Repository;

/**
 * ArticleITRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleITRepository extends \Doctrine\ORM\EntityRepository
{
}
