<?php

namespace EntityBundle\Repository;

/**
 * ArticleFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleFrRepository extends \Doctrine\ORM\EntityRepository
{
}
