<?php

namespace EntityBundle\Repository;

/**
 * ArticleEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleEnRepository extends \Doctrine\ORM\EntityRepository
{
}
