<?php

namespace EntityBundle\Repository;

/**
 * AuthorizedCommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizedCommentsRepository extends \Doctrine\ORM\EntityRepository
{
}
