<?php

namespace EntityBundle\Repository;

/**
 * CategoryITRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryITRepository extends \Doctrine\ORM\EntityRepository
{
}
