<?php

namespace EntityBundle\Repository;

/**
 * CategoryFRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryFRRepository extends \Doctrine\ORM\EntityRepository
{
}
