<?php

namespace EntityBundle\Repository;

/**
 * CategoryANRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryANRepository extends \Doctrine\ORM\EntityRepository
{
}
