<?php

namespace EntityBundle\Repository;

/**
 * CategoryArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
