<?php

namespace EntityBundle\Repository;

/**
 * SubCategoANRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoANRepository extends \Doctrine\ORM\EntityRepository
{
}
