<?php

namespace EntityBundle\Repository;

/**
 * SubCategArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
