<?php

namespace EntityBundle\Repository;

/**
 * SubCategoFRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoFRRepository extends \Doctrine\ORM\EntityRepository
{
}
