<?php

namespace EntityBundle\Repository;

/**
 * SubCategoITRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoITRepository extends \Doctrine\ORM\EntityRepository
{
}
